#!/bin/bash

# cd_backup - back up a CD for archiving - http://dvds.beandog.org/doku.php?id=cd_backup

# Requirements:
# * app-cdr/cdrdao - http://cdrdao.sourceforge.net/
# * app-cdr/cuetools - https://github.com/svend/cuetools
# * dev-libs/libcdio-paranoia - https://www.gnu.org/software/libcdio/
# * media-sound/cd-discid - https://github.com/taem/cd-discid

# See https://hydrogenaud.io/index.php/topic,28945.0.html for inspiration

device="/dev/cdrom"
test -z "$1" || device="$1"

# Get the CDDB (cd-discid package)
disc_id="$(cd-discid $device | cut -d ' ' -f 1)"
if [[ -z "$disc_id" ]]; then
	echo "Could not grab Disc ID"
	exit 1
fi

# Rip CD to one WAV file (libcdio-paranoia package)
if [[ ! -e "${disc_id}.wav" ]]; then
	cdparanoia -d $device 1- ${disc_id}.wav
fi

# Extract TOC file (cdrao package)
if [[ ! -e "${disc_id}.toc" ]]; then
	yes 1 | cdrdao read-toc --device $device --with-cddb ${disc_id}.toc
fi

# Create CUE file to TOC for added encode options (cuetools package)
if [[ ! -e "${disc_id}.cue" ]]; then
	cueconvert -i toc -o cue ${disc_id}.toc ${disc_id}.cue
fi
