#!/bin/bash

function display_usage {

	echo aac_set_track \"Track \#\" music.aac  
	exit 1

}

function is_aac {

	test "${1: -3}" == "aac"

}

function is_m4a {

	test "${1: -3}" == "m4a"

}

test $# -gt 1 || display_usage

MP4Box -itags track="$1" "$2"
MP4Box -itags name="$1" "$2"
