#!/bin/bash

function display_usage {

	echo mp3_set_artist \"Track Artist\" music.mp3  
	exit 1

}

function is_mp3 {

	test "${1: -3}" == "mp3"

}

test $# -gt 1 || display_usage

id3v2 --artist "$1" "${@:2}"
