#!/bin/bash
input="$1"
if [[ -z "$1" ]]; then echo "Need a file"; exit 1; fi
realpath=`realpath "$1"`
dirname=`dirname "$realpath"`
basename=`basename "$1" .${1: -3}`
input="${realpath}"
output="${dirname}/${basename}.m4a"

if [[ -e "$output" ]]; then exit; fi
echo "* `basename \"$input\"` -> `basename \"$output\"`" 

avconv -y -i "$input" -vn "$output" &> /dev/null

artist=$(mediainfo "$input" | grep "^Performer" | cut -d ':' -f 2- | sed -e 's/^ //g')
album=$(mediainfo "$input" | grep "^Album" | cut -d ':' -f 2- | sed -e 's/^ //g')
track=$(mediainfo "$input" | grep "^Track name " | cut -d ':' -f 2- | sed -e 's/^ //g')
tracknum=$(mediainfo "$input" | grep "^Track name/Position" | awk '{print $4}')
genre=$(mediainfo "$input" | grep "^Genre" | cut -d ':' -f 2- | sed -e 's/^ //g')

if [[ ! -z "$artist" ]]; then
	MP4Box -itags artist="$artist" "$output" &> /dev/null
fi
if [[ ! -z "$album" ]]; then
	MP4Box -itags album="$album" "$output" &> /dev/null
fi
if [[ ! -z "$track" ]]; then
	MP4Box -itags track="$track" "$output" &> /dev/null
fi
if [[ ! -z "$tracknum" ]]; then
	MP4Box -itags track=$tracknum "$output" &> /dev/null
fi
if [[ ! -z "$genre" ]]; then
	MP4Box -itags genre="$genre" "$output" &> /dev/null
fi
